services:
  opal-maintenance-db:
    container_name: opal-maintenance-db
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=opal-maintenance-db
      - POSTGRES_USER=opal-maintenance
      - POSTGRES_PASSWORD=opal-maintenance
      - PGPORT=5432
    ports:
      - "5435:5432"
    volumes:
      - opal_maintenance_db_data:/var/lib/postgresql/data  

  opal-maintenance-service:
    container_name: opal-maintenance-service
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/opal/maintenance-service
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_MAINTENANCE_DB_HOST=opal-maintenance-db
    ports:
      - $SERVER_PORT:$SERVER_PORT

volumes:
  opal_maintenance_db_data:
