apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-maintenance-service App
name: opal-maintenance-service
home: https://github.com/hmcts/opal-maintenance-service
version: 0.0.15
maintainers:
  - name: HMCTS Opal Team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
