BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;

SELECT plan(90);

-- ---------------------------------------------------------------------------
-- Scenario: The table matches the promoted column contract.
-- Setup:    Inspect table existence, column order, types and nullability.
-- Expected: Exactly the 15 TDIA columns exist with their prescribed contract.
-- ---------------------------------------------------------------------------
SELECT has_table('public', 'major_creditors', 'public.major_creditors exists');
SELECT is(
    (
        SELECT array_agg(column_name::text ORDER BY ordinal_position)
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'major_creditors'
    ),
    ARRAY[
        'major_creditor_id', 'business_unit_id', 'major_creditor_code', 'name',
        'address_line_1', 'address_line_2', 'address_line_3', 'address_line_4',
        'address_line_5', 'postcode', 'country_id', 'contact_name',
        'contact_email', 'active', 'central_authority'
    ]::text[],
    'major_creditors has exactly the promoted columns in order'
);

SELECT col_type_is('public', 'major_creditors', 'major_creditor_id', 'bigint', 'major_creditor_id is bigint');
SELECT col_type_is('public', 'major_creditors', 'business_unit_id', 'smallint', 'business_unit_id is smallint');
SELECT col_type_is('public', 'major_creditors', 'major_creditor_code', 'varchar(4)', 'major_creditor_code is varchar(4)');
SELECT col_type_is('public', 'major_creditors', 'name', 'varchar(100)', 'name is varchar(100)');
SELECT col_type_is('public', 'major_creditors', 'address_line_1', 'varchar(35)', 'address_line_1 is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'address_line_2', 'varchar(35)', 'address_line_2 is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'address_line_3', 'varchar(35)', 'address_line_3 is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'address_line_4', 'varchar(35)', 'address_line_4 is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'address_line_5', 'varchar(35)', 'address_line_5 is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'postcode', 'varchar(10)', 'postcode is varchar(10)');
SELECT col_type_is('public', 'major_creditors', 'country_id', 'bigint', 'country_id is bigint');
SELECT col_type_is('public', 'major_creditors', 'contact_name', 'varchar(35)', 'contact_name is varchar(35)');
SELECT col_type_is('public', 'major_creditors', 'contact_email', 'varchar(254)', 'contact_email is varchar(254)');
SELECT col_type_is('public', 'major_creditors', 'active', 'boolean', 'active is boolean');
SELECT col_type_is('public', 'major_creditors', 'central_authority', 'boolean', 'central_authority is boolean');

SELECT col_not_null('public', 'major_creditors', 'major_creditor_id', 'major_creditor_id is required');
SELECT col_not_null('public', 'major_creditors', 'business_unit_id', 'business_unit_id is required');
SELECT col_not_null('public', 'major_creditors', 'major_creditor_code', 'major_creditor_code is required');
SELECT col_not_null('public', 'major_creditors', 'name', 'name is required');
SELECT col_not_null('public', 'major_creditors', 'address_line_1', 'address_line_1 is required');
SELECT col_is_null('public', 'major_creditors', 'address_line_2', 'address_line_2 is optional');
SELECT col_is_null('public', 'major_creditors', 'address_line_3', 'address_line_3 is optional');
SELECT col_is_null('public', 'major_creditors', 'address_line_4', 'address_line_4 is optional');
SELECT col_is_null('public', 'major_creditors', 'address_line_5', 'address_line_5 is optional');
SELECT col_is_null('public', 'major_creditors', 'postcode', 'postcode is optional');
SELECT col_is_null('public', 'major_creditors', 'country_id', 'country_id is optional');
SELECT col_is_null('public', 'major_creditors', 'contact_name', 'contact_name is optional');
SELECT col_is_null('public', 'major_creditors', 'contact_email', 'contact_email is optional');
SELECT col_not_null('public', 'major_creditors', 'active', 'active is required');
SELECT col_not_null('public', 'major_creditors', 'central_authority', 'central_authority is required');

-- ---------------------------------------------------------------------------
-- Scenario: Major Creditor identifiers are generated by the owned sequence.
-- Setup:    Inspect the sequence, column default, dependency and configuration.
-- Expected: A non-identity BIGINT sequence starts at 1 and advances by 1.
-- ---------------------------------------------------------------------------
SELECT has_sequence('public', 'major_creditor_id_seq', 'public.major_creditor_id_seq exists');
SELECT ok(
    (
        SELECT column_default LIKE 'nextval(%major_creditor_id_seq%regclass)%'
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'major_creditors'
          AND column_name = 'major_creditor_id'
    ),
    'major_creditor_id defaults to the major_creditor_id_seq next value'
);
SELECT ok(
    EXISTS (
        SELECT 1
        FROM pg_attrdef column_default
        JOIN pg_depend default_dependency
          ON default_dependency.classid = 'pg_attrdef'::regclass
         AND default_dependency.objid = column_default.oid
         AND default_dependency.refclassid = 'pg_class'::regclass
         AND default_dependency.refobjid = 'public.major_creditor_id_seq'::regclass
        WHERE column_default.adrelid = 'public.major_creditors'::regclass
          AND column_default.adnum = (
              SELECT attribute.attnum
              FROM pg_attribute attribute
              WHERE attribute.attrelid = 'public.major_creditors'::regclass
                AND attribute.attname = 'major_creditor_id'
                AND attribute.attisdropped IS FALSE
          )
    ),
    'major_creditor_id default depends on major_creditor_id_seq'
);
SELECT ok(
    EXISTS (
        SELECT 1
        FROM pg_class sequence_relation
        JOIN pg_namespace sequence_namespace ON sequence_namespace.oid = sequence_relation.relnamespace
        JOIN pg_depend ownership_dependency
          ON ownership_dependency.classid = 'pg_class'::regclass
         AND ownership_dependency.objid = sequence_relation.oid
         AND ownership_dependency.deptype = 'a'
        JOIN pg_attribute table_attribute
          ON table_attribute.attrelid = ownership_dependency.refobjid
         AND table_attribute.attnum = ownership_dependency.refobjsubid
        WHERE sequence_relation.relkind = 'S'
          AND sequence_namespace.nspname = 'public'
          AND sequence_relation.relname = 'major_creditor_id_seq'
          AND ownership_dependency.refobjid = 'public.major_creditors'::regclass
          AND table_attribute.attname = 'major_creditor_id'
    ),
    'major_creditor_id_seq is owned by major_creditors.major_creditor_id'
);
SELECT is((SELECT data_type::text FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'major_creditor_id_seq'), 'bigint'::text, 'major_creditor_id_seq generates bigint values');
SELECT is((SELECT start_value FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'major_creditor_id_seq'), 1::bigint, 'major_creditor_id_seq starts at one');
SELECT is((SELECT increment_by FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'major_creditor_id_seq'), 1::bigint, 'major_creditor_id_seq increments by one');
SELECT is((SELECT cycle FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'major_creditor_id_seq'), FALSE, 'major_creditor_id_seq does not cycle');
SELECT is((SELECT cache_size FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'major_creditor_id_seq'), 1::bigint, 'major_creditor_id_seq caches one value');
SELECT is(
    (SELECT is_identity FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'major_creditors' AND column_name = 'major_creditor_id'),
    'NO',
    'major_creditor_id is not an identity column'
);
SELECT is(
    (
        SELECT count(*)
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'major_creditors'
          AND column_name <> 'major_creditor_id'
          AND column_default IS NOT NULL
    ),
    0::bigint,
    'no non-identifier column has a default'
);

-- ---------------------------------------------------------------------------
-- Scenario: Column comments preserve the authoritative descriptions.
-- Setup:    Read every comment in physical column order.
-- Expected: All 15 descriptions match the promoted TDIA verbatim.
-- ---------------------------------------------------------------------------
SELECT is(
    (
        SELECT array_agg(col_description(table_attribute.attrelid, table_attribute.attnum) ORDER BY table_attribute.attnum)
        FROM pg_attribute table_attribute
        WHERE table_attribute.attrelid = 'public.major_creditors'::regclass
          AND table_attribute.attnum > 0
          AND table_attribute.attisdropped IS FALSE
    ),
    ARRAY[
        'Database-generated primary key',
        'Owning RM Business Unit',
        'Business key, unique within the Business Unit',
        'Major Creditor display name',
        'Address line 1', 'Address line 2', 'Address line 3', 'Address line 4', 'Address line 5',
        'Postcode',
        'Reference to Country',
        'Named contact',
        'Contact email address',
        'Whether the record is available for new selection',
        'Whether the Major Creditor is also a Central Authority'
    ]::text[],
    'column comments match the verbatim TDIA descriptions in column order'
);

-- ---------------------------------------------------------------------------
-- Scenario: Keys and relationships enforce the promoted integrity contract.
-- Setup:    Inspect constraint names, types, columns and referenced columns.
-- Expected: One PK, one composite unique constraint and both FKs match TDIA.
-- ---------------------------------------------------------------------------
SELECT has_pk('public', 'major_creditors', 'major_creditors has a primary key');
SELECT col_is_pk('public', 'major_creditors', 'major_creditor_id', 'major_creditor_id is the primary key');
SELECT ok(
    EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.major_creditors'::regclass
          AND conname = 'major_creditors_pk'
          AND contype = 'p'
    ),
    'the primary key is named major_creditors_pk'
);
SELECT has_unique('public', 'major_creditors', 'major_creditors has a unique constraint');
SELECT ok(
    EXISTS (
        SELECT 1
        FROM pg_constraint table_constraint
        WHERE table_constraint.conrelid = 'public.major_creditors'::regclass
          AND table_constraint.conname = 'mc_business_unit_id_major_creditor_code_uk'
          AND table_constraint.contype = 'u'
          AND table_constraint.conkey = ARRAY[
              (SELECT attnum FROM pg_attribute WHERE attrelid = 'public.major_creditors'::regclass AND attname = 'business_unit_id' AND attisdropped IS FALSE),
              (SELECT attnum FROM pg_attribute WHERE attrelid = 'public.major_creditors'::regclass AND attname = 'major_creditor_code' AND attisdropped IS FALSE)
          ]::smallint[]
    ),
    'the promoted composite unique constraint protects business_unit_id and major_creditor_code'
);
SELECT ok(
    EXISTS (
        SELECT 1
        FROM pg_constraint table_constraint
        WHERE table_constraint.conrelid = 'public.major_creditors'::regclass
          AND table_constraint.confrelid = 'public.business_units'::regclass
          AND table_constraint.conname = 'mc_business_unit_id_fk'
          AND table_constraint.contype = 'f'
          AND table_constraint.confupdtype = 'a'
          AND table_constraint.confdeltype = 'a'
          AND table_constraint.conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'public.major_creditors'::regclass AND attname = 'business_unit_id' AND attisdropped IS FALSE)]::smallint[]
          AND table_constraint.confkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'public.business_units'::regclass AND attname = 'business_unit_id' AND attisdropped IS FALSE)]::smallint[]
    ),
    'mc_business_unit_id_fk references business_units.business_unit_id with default actions'
);
SELECT ok(
    EXISTS (
        SELECT 1
        FROM pg_constraint table_constraint
        WHERE table_constraint.conrelid = 'public.major_creditors'::regclass
          AND table_constraint.confrelid = 'public.countries'::regclass
          AND table_constraint.conname = 'mc_country_id_fk'
          AND table_constraint.contype = 'f'
          AND table_constraint.confupdtype = 'a'
          AND table_constraint.confdeltype = 'a'
          AND table_constraint.conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'public.major_creditors'::regclass AND attname = 'country_id' AND attisdropped IS FALSE)]::smallint[]
          AND table_constraint.confkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'public.countries'::regclass AND attname = 'country_id' AND attisdropped IS FALSE)]::smallint[]
    ),
    'mc_country_id_fk references countries.country_id with default actions'
);

-- ---------------------------------------------------------------------------
-- Scenario: The three promoted access paths use explicit non-unique B-trees.
-- Setup:    Inspect index names, ordered columns, access methods and uniqueness.
-- Expected: Each TDIA index exists exactly as designed.
-- ---------------------------------------------------------------------------
SELECT has_index('public', 'major_creditors', 'major_creditors_business_unit_id_idx', ARRAY['business_unit_id'], 'the business unit index uses business_unit_id');
SELECT index_is_type('public', 'major_creditors', 'major_creditors_business_unit_id_idx', 'btree', 'the business unit index is a btree');
SELECT is((SELECT indisunique FROM pg_index JOIN pg_class ON pg_class.oid = indexrelid WHERE pg_class.relname = 'major_creditors_business_unit_id_idx'), FALSE, 'the business unit index is not unique');
SELECT has_index('public', 'major_creditors', 'major_creditors_country_id_idx', ARRAY['country_id'], 'the country index uses country_id');
SELECT index_is_type('public', 'major_creditors', 'major_creditors_country_id_idx', 'btree', 'the country index is a btree');
SELECT is((SELECT indisunique FROM pg_index JOIN pg_class ON pg_class.oid = indexrelid WHERE pg_class.relname = 'major_creditors_country_id_idx'), FALSE, 'the country index is not unique');
SELECT has_index('public', 'major_creditors', 'major_creditors_central_authority_active_idx', ARRAY['central_authority', 'active'], 'the Central Authority index uses central_authority and active in order');
SELECT index_is_type('public', 'major_creditors', 'major_creditors_central_authority_active_idx', 'btree', 'the Central Authority index is a btree');
SELECT is((SELECT indisunique FROM pg_index JOIN pg_class ON pg_class.oid = indexrelid WHERE pg_class.relname = 'major_creditors_central_authority_active_idx'), FALSE, 'the Central Authority index is not unique');

-- ---------------------------------------------------------------------------
-- Scenario: Test-owned Major Creditor fixture space is unused.
-- Setup:    Inspect only the two reserved Business Unit identifiers.
-- Expected: No Major Creditor fixture exists; unrelated records are allowed.
-- ---------------------------------------------------------------------------
SELECT is((SELECT count(*) FROM public.major_creditors WHERE business_unit_id IN (32001, 32002)), 0::bigint, 'test-owned Major Creditor fixture space is unused');

-- ---------------------------------------------------------------------------
-- Scenario: Test-owned prerequisite rows support isolated relationship checks.
-- Setup:    Insert two Business Units and one Country inside this transaction.
-- Expected: All prerequisite fixtures are accepted and roll back with the test.
-- ---------------------------------------------------------------------------
SELECT lives_ok(
    $sql$INSERT INTO public.business_units (business_unit_id, business_unit_code, business_unit_name, business_unit_type, welsh_language)
         VALUES (32001, 'M001', 'pgTAP Major Creditor Unit One', 'Area', FALSE)$sql$,
    'the first test-owned Business Unit can be inserted'
);
SELECT lives_ok(
    $sql$INSERT INTO public.business_units (business_unit_id, business_unit_code, business_unit_name, business_unit_type, welsh_language)
         VALUES (32002, 'M002', 'pgTAP Major Creditor Unit Two', 'Area', FALSE)$sql$,
    'the second test-owned Business Unit can be inserted'
);
SELECT lives_ok(
    $sql$INSERT INTO public.countries (country_id, cjs_code, country_name, date_used_from, active)
         VALUES (990001, 32001, 'pgTAP Major Creditor Country', DATE '2026-01-01', TRUE)$sql$,
    'the test-owned Country can be inserted'
);

-- ---------------------------------------------------------------------------
-- Scenario: Complete and minimal valid rows are accepted.
-- Setup:    Insert one row at every varchar limit and one omitting all nullable fields.
-- Expected: Both insert, receive distinct generated IDs, and retain both flags.
-- ---------------------------------------------------------------------------
SELECT lives_ok(
    $sql$
    INSERT INTO public.major_creditors (
        business_unit_id, major_creditor_code, name,
        address_line_1, address_line_2, address_line_3, address_line_4, address_line_5,
        postcode, country_id, contact_name, contact_email, active, central_authority
    ) VALUES (
        32001, 'B001', repeat('N', 100),
        repeat('1', 35), repeat('2', 35), repeat('3', 35), repeat('4', 35), repeat('5', 35),
        repeat('P', 10), 990001, repeat('C', 35), repeat('E', 254), TRUE, TRUE
    )
    $sql$,
    'a complete row at every varchar boundary can be inserted'
);
SELECT lives_ok(
    $sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority)
         VALUES (32001, 'M001', 'Minimal Major Creditor', 'Address line one', FALSE, FALSE)$sql$,
    'a valid row may omit every nullable field'
);
SELECT ok(
    (SELECT count(*) = 2 AND count(major_creditor_id) = 2 AND min(major_creditor_id) <> max(major_creditor_id) FROM public.major_creditors WHERE business_unit_id = 32001 AND major_creditor_code IN ('B001', 'M001')),
    'omitted identifiers receive distinct sequence-generated values'
);
SELECT results_eq(
    $$SELECT active, central_authority FROM public.major_creditors WHERE business_unit_id = 32001 AND major_creditor_code = 'B001'$$,
    'VALUES (TRUE, TRUE)',
    'active and central_authority retain explicit true values'
);

-- ---------------------------------------------------------------------------
-- Scenario: Every mandatory column rejects NULL.
-- Setup:    Attempt otherwise-valid inserts with each required value set to NULL.
-- Expected: Each insert raises SQLSTATE 23502.
-- ---------------------------------------------------------------------------
SELECT throws_ok($sql$INSERT INTO public.major_creditors (major_creditor_id, business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (NULL, 32001, 'N001', 'Null ID', 'Address', TRUE, FALSE)$sql$, '23502', NULL, 'null major_creditor_id is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (NULL, 'N002', 'Null Unit', 'Address', TRUE, FALSE)$sql$, '23502', NULL, 'null business_unit_id is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, NULL, 'Null Code', 'Address', TRUE, FALSE)$sql$, '23502', NULL, 'null major_creditor_code is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'N004', NULL, 'Address', TRUE, FALSE)$sql$, '23502', NULL, 'null name is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'N005', 'Null Address', NULL, TRUE, FALSE)$sql$, '23502', NULL, 'null address_line_1 is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'N006', 'Null Active', 'Address', NULL, FALSE)$sql$, '23502', NULL, 'null active is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'N007', 'Null Authority', 'Address', TRUE, NULL)$sql$, '23502', NULL, 'null central_authority is rejected');

-- ---------------------------------------------------------------------------
-- Scenario: Every bounded text column rejects a value above its limit.
-- Setup:    Attempt inserts one character beyond each declared varchar length.
-- Expected: Each insert raises SQLSTATE 22001.
-- ---------------------------------------------------------------------------
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'LONG1', 'Long Code', 'Address', TRUE, FALSE)$sql$, '22001', NULL, 'major_creditor_code longer than four characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'L002', repeat('N', 101), 'Address', TRUE, FALSE)$sql$, '22001', NULL, 'name longer than 100 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority) VALUES (32001, 'L003', 'Long Address One', repeat('1', 36), TRUE, FALSE)$sql$, '22001', NULL, 'address_line_1 longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, address_line_2, active, central_authority) VALUES (32001, 'L004', 'Long Address Two', 'Address', repeat('2', 36), TRUE, FALSE)$sql$, '22001', NULL, 'address_line_2 longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, address_line_3, active, central_authority) VALUES (32001, 'L005', 'Long Address Three', 'Address', repeat('3', 36), TRUE, FALSE)$sql$, '22001', NULL, 'address_line_3 longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, address_line_4, active, central_authority) VALUES (32001, 'L006', 'Long Address Four', 'Address', repeat('4', 36), TRUE, FALSE)$sql$, '22001', NULL, 'address_line_4 longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, address_line_5, active, central_authority) VALUES (32001, 'L007', 'Long Address Five', 'Address', repeat('5', 36), TRUE, FALSE)$sql$, '22001', NULL, 'address_line_5 longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, postcode, active, central_authority) VALUES (32001, 'L008', 'Long Postcode', 'Address', repeat('P', 11), TRUE, FALSE)$sql$, '22001', NULL, 'postcode longer than 10 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, contact_name, active, central_authority) VALUES (32001, 'L009', 'Long Contact', 'Address', repeat('C', 36), TRUE, FALSE)$sql$, '22001', NULL, 'contact_name longer than 35 characters is rejected');
SELECT throws_ok($sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, contact_email, active, central_authority) VALUES (32001, 'L010', 'Long Email', 'Address', repeat('E', 255), TRUE, FALSE)$sql$, '22001', NULL, 'contact_email longer than 254 characters is rejected');

-- ---------------------------------------------------------------------------
-- Scenario: Primary, unique and foreign-key rules reject invalid rows.
-- Setup:    Reuse identifiers/codes and reference absent prerequisite rows.
-- Expected: Uniqueness raises 23505, missing references raise 23503, while the
--           same creditor code in a different Business Unit remains valid.
-- ---------------------------------------------------------------------------
SELECT throws_ok(
    $sql$INSERT INTO public.major_creditors (major_creditor_id, business_unit_id, major_creditor_code, name, address_line_1, active, central_authority)
         SELECT major_creditor_id, 32001, 'D001', 'Duplicate ID', 'Address', TRUE, FALSE FROM public.major_creditors WHERE business_unit_id = 32001 AND major_creditor_code = 'B001'$sql$,
    '23505', NULL, 'a duplicate major_creditor_id is rejected'
);
SELECT throws_ok(
    $sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority)
         VALUES (32001, 'B001', 'Duplicate Unit Code', 'Address', TRUE, FALSE)$sql$,
    '23505', NULL, 'a duplicate creditor code in the same Business Unit is rejected'
);
SELECT lives_ok(
    $sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority)
         VALUES (32002, 'B001', 'Same Code Other Unit', 'Address', TRUE, FALSE)$sql$,
    'the same creditor code is allowed in a different Business Unit'
);
SELECT throws_ok(
    $sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, active, central_authority)
         VALUES (32767, 'F001', 'Unknown Unit', 'Address', TRUE, FALSE)$sql$,
    '23503', NULL, 'an unknown business_unit_id is rejected'
);
SELECT throws_ok(
    $sql$INSERT INTO public.major_creditors (business_unit_id, major_creditor_code, name, address_line_1, country_id, active, central_authority)
         VALUES (32001, 'F002', 'Unknown Country', 'Address', 9223372036854775807, TRUE, FALSE)$sql$,
    '23503', NULL, 'an unknown country_id is rejected'
);

SELECT * FROM finish();
ROLLBACK;
